from __future__ import annotations
from pathlib import Path
from typing import List, Dict, Any, Optional
from models.dataset import Dataset
from models.field import DataType
from models.relationship import Relationship
from .base import BaseExporter


class SqlExporter(BaseExporter):
    """Generates production PostgreSQL and Supabase DDL schemas and transactional INSERT statements."""

    def __init__(self):
        super().__init__(name="sql", extension="sql")

    @staticmethod
    def map_sql_type(dtype: DataType) -> str:
        mapping = {
            DataType.STRING: "TEXT",
            DataType.INTEGER: "INTEGER",
            DataType.FLOAT: "NUMERIC(12, 4)",
            DataType.BOOLEAN: "BOOLEAN",
            DataType.DATE: "DATE",
            DataType.LIST: "TEXT[]",
            DataType.JSON: "JSONB",
        }
        return mapping.get(dtype, "TEXT")

    def generate_ddl(self, datasets: List[Dataset], relationships: Optional[List[Relationship]] = None) -> str:
        sql_lines = [
            "-- ========================================================",
            "-- Darkroom DataForge: Generated PostgreSQL / Supabase Schema",
            "-- Platform: Wits–merSETA Darkroom Data Engineering",
            "-- ========================================================\n",
            "BEGIN;\n"
        ]

        # 1. CREATE TABLE statements
        for ds in datasets:
            table_name = ds.metadata.name
            sql_lines.append(f"-- Table: {table_name}")
            sql_lines.append(f"-- Description: {ds.metadata.description or 'Auto-generated by Darkroom DataForge'}")
            sql_lines.append(f"CREATE TABLE IF NOT EXISTS {table_name} (")
            
            col_defs = []
            for col in ds.columns:
                sql_type = self.map_sql_type(col.data_type)
                null_clause = "NOT NULL" if col.required else "NULL"
                col_defs.append(f"    {col.name} {sql_type} {null_clause}")

            # Primary Key
            if ds.primary_key:
                pk_cols = ", ".join(ds.primary_key)
                col_defs.append(f"    CONSTRAINT pk_{table_name} PRIMARY KEY ({pk_cols})")

            sql_lines.append(",\n".join(col_defs))
            sql_lines.append(");\n")

        # 2. Foreign Key constraints
        if relationships:
            for rel in relationships:
                if rel.is_accepted:
                    fk_sql = (
                        f"ALTER TABLE {rel.child_dataset} "
                        f"ADD CONSTRAINT fk_{rel.child_dataset}_{rel.parent_dataset} "
                        f"FOREIGN KEY ({rel.foreign_key}) REFERENCES {rel.parent_dataset}({rel.parent_key}) "
                        f"ON DELETE CASCADE;"
                    )
                    sql_lines.append(fk_sql)
            sql_lines.append("")

        # 3. Data Ingestion Statements
        for ds in datasets:
            table_name = ds.metadata.name
            if not ds.records:
                continue

            sql_lines.append(f"-- Ingestion: {table_name} ({len(ds.records)} rows)")
            col_names = [c.name for c in ds.columns]
            cols_str = ", ".join(col_names)

            for rec in ds.records:
                vals = []
                for c in ds.columns:
                    val = rec.get_value(c.name, prefer_normalized=True)
                    if val is None:
                        vals.append("NULL")
                    elif isinstance(val, bool):
                        vals.append("TRUE" if val else "FALSE")
                    elif isinstance(val, (int, float)):
                        vals.append(str(val))
                    else:
                        escaped = str(val).replace("'", "''")
                        vals.append(f"'{escaped}'")
                vals_str = ", ".join(vals)
                sql_lines.append(f"INSERT INTO {table_name} ({cols_str}) VALUES ({vals_str});")
            sql_lines.append("")

        sql_lines.append("COMMIT;\n")
        return "\n".join(sql_lines)

    def export_dataset(
        self,
        dataset: Dataset,
        output_path: str,
        include_provenance: bool = False,
        prefer_normalized: bool = True
    ) -> str:
        return self.export_all([dataset], str(Path(output_path).parent))[0]

    def export_all(
        self,
        datasets: List[Dataset],
        output_directory: str,
        include_provenance: bool = False,
        prefer_normalized: bool = True
    ) -> List[str]:
        out_dir = Path(output_directory).resolve()
        out_dir.mkdir(parents=True, exist_ok=True)
        schema_file = out_dir / "schema.sql"

        sql_content = self.generate_ddl(datasets)
        with open(schema_file, "w", encoding="utf-8") as f:
            f.write(sql_content)

        return [str(schema_file)]
